### ISSUE TITLE
有考虑支持twirp里的 Import mapping parameter吗？

### ISSUE THREAD

**Issue by busyfree** [go-kiss/protoc-gen-markdown#5]
proto文件导入公用文件之后，protoc-gen-markdown 再输出markdown就失败了。

**Comment by lvht** [comment]
@busyfree 已经解决了～另外我在搞一个重构（简化）版本，也可以关注一下。

https://github.com/lvht/protoc-gen-markdown/blob/v2/hello.md

**Comment by lvht** [comment]
开 MR 了 https://github.com/go-kiss/protoc-gen-markdown/pull/6
